### ISSUE TITLE
Mouse buttons stop working after the following action

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/three.js#24]
- Click on Scene tab/Scene item
- Click on green arrow that appears

Tested only on Windows/Chrome/Python3.5.2.

**Comment by aymanhab** [comment]
Is that the translate arrow?

**Comment by tkuchida** [comment]
> Is that the translate arrow?

Yes. Same issue if you click one of the "planar translation" squares.

**Comment by aymanhab** [comment]
Reproduced in three.js editor, due to trying to find parent of scene (which is null). Fix on the way. Thanks @tkuchida

**Comment by aymanhab** [comment]
Fix submitted, please test with next alpha or live on master and close accordingly.

**Comment by tkuchida** [comment]
:+1:
