### ISSUE TITLE
Spec. what the Visualizer alpha contains

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/three.js#5]
For Alpha release of Visualizer we want to test/explore and get feedback on:
- Navigation: Mouse keys
- Built-in views (X,Y,Z)
- Taking static images
- Move/insert lights/control shadows
- Change scenes and ground
- Built in motions/movie-making utilities

**Comment by aymanhab** [comment]
Ideally this works cross platform and includes some built in motion to test camera control.

**Comment by aymanhab** [comment]
Any feedback or thoughts @aseth1 @chrisdembia @jenhicks @camilletown

**Comment by jenhicks** [comment]
This list looks good to me. Thanks @aymanhab !

**Comment by aymanhab** [comment]
I believe this all has been included. Will close this one so we have room for specific issues
