### ISSUE TITLE
Muscles (GeometryPaths) need end-caps

### ISSUE THREAD

**Issue by aseth1** [opensim-org/three.js#68]
##### Currently GeometryPaths are drawn as smooth tubes, but they are open.  They should be capped either by a sphere at each end or by tapering the skinned mesh.

Here is an example of what it looks like:
![opensim_open_cylinder](https://user-images.githubusercontent.com/6494122/28297053-a6f053b4-6b20-11e7-97f0-104b80d4ddce.jpg)

##### Three.js version

- [ ] Dev
- [ ] r77
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by aseth1** [comment]
@tkuchida in a brief discussion with @aymanhab he mentioned preferring not to introduce additional geometry (i.e. spheres) and use the skinning of the cylinders to create a taper at each end.

**Comment by tkuchida** [comment]
> in a brief discussion with @aymanhab he mentioned preferring not to introduce additional geometry (i.e. spheres) and use the skinning of the cylinders to create a taper at each end.

Sounds fine. I just don't think users should be able to see the inside of the muscle cylinder; how that's implemented isn't as important.

**Comment by aymanhab** [comment]
fixed years ago, closing
